apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NGNlNzg5Yi1rcjEtcmVnaXN0cnkuY29udGFpbmVyLm5obmNsb3VkLmNvbS9jb250YWluZXItcGxhdGZvcm0tcmVnaXN0cnkiOnsidXNlcm5hbWUiOiJYQ0ExT2owRnFBOE9NaGFsT1VoSyIsInBhc3N3b3JkIjoiekdneG83WGxwazVvalk3diIsImF1dGgiOiJXRU5CTVU5cU1FWnhRVGhQVFdoaGJFOVZhRXM2ZWtkbmVHODNXR3h3YXpWdmFsazNkZz09In19fQ==
kind: Secret
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  name: ncr
  namespace: iot-edge
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-back
  labels:
    app: test-back
    cluster: kpaas-k2p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-back
      cluster: kpaas-k2p
  template:
    metadata:
      labels:
        app: test-back
        cluster: kpaas-k2p
    spec:
      imagePullSecrets:
        - name: ncr
      containers:
      - name: test-back
        image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/test-back:latest
        ports:
        - containerPort: 8080
        env:
        - name: multi
          value: "test"

---
apiVersion: v1
kind: Service
metadata:
  name: test-back
spec:
  selector:
    app: test-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090
  type: NodePort
