apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-back
  labels:
    app: test-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-back
  template:
    metadata:
      labels:
        app: test-back
    spec:
      containers:
      - name: test-back
        image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/test-back:latest
        ports:
        - containerPort: 8080
        env:
        - name: multi
          value: "test"

---
apiVersion: v1
kind: Service
metadata:
  name: test-back
spec:
  selector:
    app: test-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
